### ISSUE TITLE
No reply value from websocket handler will crash all the websockets that are serviced

### ISSUE THREAD

**Issue by ashneyderman** [ChicagoBoss/ChicagoBoss#168]
by the same service.

here is the sample that will produce the above mentioned behavior:

-module(nm_demo_websocket).

...

handle_close(_ServiceURL, _WebSocket, _SessionId, _State) ->
  {noreply, State}.

If you open up two separate browsers and simply close the page of one of them the other one will stop working.

**Comment by danikp** [comment]
a lot of things change since 2012, including #614, so please open new issue if problem still persist
