### ISSUE TITLE
Streaming without chunks

### ISSUE THREAD

**Issue by davidw** [ChicagoBoss/ChicagoBoss#182]
Hi,

One thing that I may or may not be calling on CB to do is to be the endpoint for an HTML5 <video> tag, as in src="/some/path", where the controller will start pulling data from some video source.

This data needs to be streamed "raw", no chunks.  One acceptable way of doing this would simply be to grab the socket, send some headers, and go to work, but it'd be nice to make things a bit cleaner and document them.

**Comment by danikp** [comment]
looks like there is solutions for that issue. closing.
