### ISSUE TITLE
New elixir code causes crash during rebar compile

### ISSUE THREAD

**Issue by davidw** [ChicagoBoss/ChicagoBoss#189]
1. Update CB code to master.
2. Create a new app.
3. cd to new app
4. ./rebar compile.

Crash:

    The on_load function for module Elixir-URI returned {undef,
                                                     [{'Elixir-Enum',each,
                                                       [['Elixir-URI-FTP',
                                                         'Elixir-URI-HTTP'|...],
                                                        #Fun<Elixir-Code.ensure_loaded.1>],
                                                       []},
                                                      {'Elixir-URI',
                                                       preload_parsers,0,
                                                       [{...}|...]},
                                                      {code_server,
                                                       '-handle_on_load/4-fun-0-',
                                                       1,
                                                       [...]}]}

    =ERROR REPORT==== 22-Jan-2013::16:17:52 ===
    Error in process <0.49.0> with exit value: {undef,[{'Elixir-Enum',each,[['Elixir-URI-FTP','Elixir-URI-HTTP','Elixir-URI-HTTPS','Elixir-URI-LDAP','Elixir-URI-SFTP','Elixir-URI-TFTP'],#Fun<Elixir-Code.ensure_loaded.1>],[]},{'Elixir-URI',preload_parsers,0,[{file,"/home/davidw/workshop/ChicagoBoss/dep...

**Comment by danikp** [comment]
closing, please re-open if it's still an issue
