### ISSUE TITLE
UTF-8 characters in controller

### ISSUE THREAD

**Issue by Zet-one** [ChicagoBoss/ChicagoBoss#270]
I make list and some fields of them contain utf-8 characters,
and its stop to work:

`CRASH REPORT Process <0.154.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([[<<"<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\" />\n\t<link rel=\"stylesheet\" href=\"...">>,...],...]) in mochiweb_request:respond/2 line 337`

If I change list from
`erlang[{menu, id, "Клиенты", "client"}]`
     to
`erlang[{menu, id, [208,154,208,187,208,184,208,181,208,189,209,130,209,139], "client"}]`

its work fine, but my menu_helper looks bad in this way.

Also i try to change function iolist_size in file mochiweb_request with this

``` erlang
-compile({no_auto_import,[iolist_size/1]}).
iolist_size([F | Rest] = List) ->
    iolist_size(List, 0);

iolist_size(Bin) ->
    List = binary_to_list(Bin),
    iolist_size(List, 0).


iolist_size([], Count) -> Count;
iolist_size([_First| Rest], Count) -> iolist_size(Rest, Count +1).
```

But its not help, coz I think: I compile this file with wrong "internal.hrl" or some other reason.

Can u make something with `erlang iolist_size("Some UTF-8 chars ываыва").` in ChicagoBoss, coz this function throw bad argument error in latest version of Erlang also.

**Comment by cuciferus** [comment]
Ok I'm having a similar issue but I cannot solve it with unicode:characters_to_list :
 Pacient = pacient:new(unicode:characters_to_list("Ştefan"), unicode:characters_to_list("Bănică"), "182092", "at home", "0768").
Pacient:save() goes
 exception exit: {{{badarg,[{erlang,list_to_binary,
                                      [[66,259,110,105,99,259]]

I'm using a postgresql db and trying to insert the same values from pgsql works.
Any ideas how to fix this?

**Comment by choptastic** [comment]
Hi,

Have you tried using unicode:characters_to_binary instead of
unicode:characters_to_list?

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by cuciferus** [comment]
Hello! Yup that did the trick.Thanks you! Any ideas how to enable this transformation by default? I've noticed I need this in many models
