### ISSUE TITLE
validation_tests/0 vs validation_tests/1

### ISSUE THREAD

**Issue by timClicks** [ChicagoBoss/ChicagoBoss#272]
I find the following paragraph in the [BossDB documentation](http://www.chicagoboss.org/api-db.html) unclear. How do I access `on_create` and `on_update`?

> ```validate_record(RecordBossRecord, IsNew) -> ok | {error, [ErrorMessages]}```
>
> Validate the given BossRecord without saving it in the database. ErrorMessages are generated from the list of tests returned by the BossRecord's `validation_tests/1` function (if defined), where parameter is atom() `on_create` | `on_update`. The returned list should consist of {TestFunction, ErrorMessage} tuples, where TestFunction is a fun of arity 0 that returns true if the record is valid or false if it is invalid. ErrorMessage should be a (constant) string which will be included in ErrorMessages if the TestFunction returns false on this particular BossRecord.

I have attempted to make use of this functionality by trial and error...

```erlang
-module(person, [Id, Name, Description]).
-compile(export_all).

 validation_tests(Status) when Status =:= on_create ->
  [{fun() ->
    boss_db:count(person, [name, equals, Name]) =:= 0 end,
    "Name must be unique"}].
```
...which doesn't seem to ever get called. Instead, I need to revert to the following to achieve a similar result:

```erlang
-module(person, [Id, Name, Description]).
-compile(export_all).

validation_tests() ->
  [{fun() ->
    case Id of
       id -> boss_db:count(person, [name, equals, Name]) =:= 0;
       _ -> true
    end
  end, "Name must be unique"}].
```

**Comment by danikp** [comment]
please re-open if problem still persist
