### ISSUE TITLE
init.sh doesn't stop the running process when in production mode

### ISSUE THREAD

**Issue by kotedo** [ChicagoBoss/ChicagoBoss#282]
The init.sh shell script doesn't get the correct hostname setup when it parses boss.config to stop the server.

{vm_name, "mycoolapp@mycoolserver.local"} is set, and yet the init.sh script ventures out to get the hostname, but misses the domain, thus producing an error message that's been send to /dev/null; so no error is visible even though it fails.

Example of the generated command line:

``` bash
erl -noshell -pa ebin -setcookie mycoolapp_cookie_jar -sname stopper_mycoolapp@mycoolserver -eval "rpc:call('mycoolapp@mycoolserver', init, stop, [])." -s init stop
```

The error message generated when the roc:call() is executed is:

``` erlang
(mycoolapp@mycoolserver.local)1> rpc:call('mycoolapp@mycoolserver', init, stop, []).
18:03:11.362 [error] ** System running to use fully qualified hostnames **
** Hostname mycoolserver is illegal **

{badrpc,nodedown}
```

**Comment by justgage** [comment]
I'm not sure this is related to this issue but I was going through the get started guide and noticed that `./init stop` doesn't actually stop the server even though it says it does which is quite confusing as a beginner.

**Comment by kotedo** [comment]
That's a known old issue.  Take a peek at the issues on GitHub for ChicagoBoss.

--Kai
