### ISSUE TITLE
CB should take respect on deps_dir at rebar.config

### ISSUE THREAD

**Issue by ztmr** [ChicagoBoss/ChicagoBoss#303]
There are places, typically in rebar boss_plugin where "./deps" are expected to exists.

Main reasons:
- having CB apps as dependency of other apps (so they have boss_dir as "../")
- having all the deps shared (system-wide directory) across all the applications (even if they're not related to each other)
- avoid symlinking as it leads to recursive dependency recompilation

(Of course, when one app needs another version of dependencies than another one, these cases are to be solved individually.)

Another thing is that even if the CB itself is a dependency in (expected "deps" dir), it is necessary to write "./deps/boss" in boss.config instead of "deps/boss" -- just a note, no big deal. Leaving boss path emty defaults back to (expected) "deps" dir...

**Comment by danikp** [comment]
too old, please reopen if issue still exists
