### ISSUE TITLE
Installation error on Windows 8.1

### ISSUE THREAD

**Issue by houdelou** [ChicagoBoss/ChicagoBoss#453]
Hi, I want to try Chicago Boss but I have an error when I follow the quickstart guide. I installed R16B02 x64 and downloaded Chicago Boss. I run windows-make.bat and get error messages as following:

WARN: Expected /path/to/chicago/deps/boss_db to be an app dir (containing ebin/*.app) but no app found.

I'm new to Erlang so maybe this is a newbie problem but I would be glad if you add some instructions, if any missing, for newbies.

Thanks

**Comment by danikp** [comment]
closing
