### ISSUE TITLE
./init.sh: eval: line 16: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by jusfeel** [ChicagoBoss/ChicagoBoss#480]
I cloned boss in CentOS and did "make" and got "congratuations!" message. Everything seems fine. Then I created a project, changed boss.config to use the path that I installed the boss previously and run into this errors..
./init-dev.sh
./init.sh: eval: line 16: syntax error near unexpected token `('
./init.sh: eval: line 16: `WARN:  Expected /opt/www/vuasai/deps/boss to be an app dir (containing ebin/*.app), but no .app found.'

Any help would be appreciated!

**Comment by jusfeel** [comment]
Just to update, I just tried the new boss v0.8.15, the issue persists. Still, I have to recompile a boss under my project. I cannot reference the boss from which I "make app PROJECT=xxx".

**Comment by danikp** [comment]
is that problem still persists ?

**Comment by jusfeel** [comment]
Not any more.

**Comment by danikp** [comment]
great to hear, closing
