### ISSUE TITLE
Issue with Cowboy but not mochiweb

### ISSUE THREAD

**Issue by choptastic** [ChicagoBoss/ChicagoBoss#494]
This must be found out what's causing the crash!

Cross-referenced from the mailing list.

https://groups.google.com/d/msgid/chicagoboss/CANnHf0PANHBG%2BFkF%3DZjFNgHhcHjkTDs6SosLkGB5XAbO5z5JpQ%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by danikp** [comment]
unable reproduce with latest master, after merging #614
