### ISSUE TITLE
maps's error not throw 

### ISSUE THREAD

**Issue by dcy** [ChicagoBoss/ChicagoBoss#529]
I update my aleppo to the latest version, and i can use maps.
If Account is maps. And "Account:id()" not throw any error.
It should be:
exception error: bad argument
in function apply/3
called as apply(#{key => value},id,[])

No error and i can't debug my code.
I don't know it's ChicagoBoss's bug, or aleppo's.

**Comment by danikp** [comment]
recently, number of dependencies updated to support maps, including erlydtl, aleppo, boss_db and lager. Try to update to latest versions of all of them, it may solve that specific issue. lager could be helpful one.

**Comment by danikp** [comment]
please reopen this issue, if problem still persist
