### ISSUE TITLE
boss_db_pmod_pt not handle map

### ISSUE THREAD

**Issue by dcy** [ChicagoBoss/ChicagoBoss#532]
The code: NewAccount = Account#{password_hash => NewHash},
The error:
ERROR: pre_compile failed while processing /home/dcy/yxq: {'EXIT',
    {function_clause,
        [{boss_db_pmod_pt,expr,
             [{map,200,
                  {var,200,'Account'},
                  [{map_field_assoc,200,
                       {atom,200,password_hash},
                       {var,200,'NewHash'}}]},
              {pmod,
                  ['Req'],
                  {28,
                   {{my_blacklist,2},
                    {{change_name,2},
                     {{already_games,2},
                      {{activate,2},
                       {{'_routes',0},nil,nil},
                       {{add_blacklist,2},nil,nil}},
                      {{cancel_blacklist,2},
                       {{avatar,2},nil,nil},
                       {{cancel_follow,2},nil,nil}}},
                     {{followings,2},
                      {{follow,2},
                       {{change_password,2},nil,nil},
                       {{followers,2},nil,nil}},
                      {{logout,2},{{login,2},nil,nil},nil}}},
                    {{register,2},
                     {{people,2},
                      {{my_followings,2},
                       {{my_followers,2},nil,nil},
                       {{participate_games,2},nil,nil}},
                      {{profile,2},{{personal_homepage,2},nil,nil},nil}},
                     {{update_description,2},
                      {{reset_password,2},
                       {{req_reset_password,2},nil,nil},
                       {{timelines,2},nil,nil}},
                      {{want_games,2},
                       {{update_signature,2},nil,nil},
                       nil}}}}}}],
             [{file,"src/boss_db_pmod_pt.erl"},{line,296}]},
Not every code like this will throw error, the code in other location will not throw error.

**Comment by danikp** [comment]
@dcy, thanks for a patch, closing
