### ISSUE TITLE
chicagoboss headers are of mochiweb although server is set to cowboy

### ISSUE THREAD

**Issue by himangshuj** [ChicagoBoss/ChicagoBoss#538]
curl -I localhost:8001/api/xxxx
HTTP/1.1 200 OK
Server: MochiWeb/1.0 (Any of you quaids got a smint?)
Date: Mon, 05 Jan 2015 13:25:41 GMT
Content-Type: text/html
Content-Length: 49

config is 
      {server,cowboy},
      {session_adapter,cache},
      {session_cookie_http_only,false},
      {session_cookie_secure,false},

**Comment by choptastic** [comment]
ChicagoBoss currently runs cowboy through mochicow, which provides a mochiweb API on top of the Cowboy underlying server. Hence the quads and smints.

**Comment by danikp** [comment]
closing
