### ISSUE TITLE
Websocket Problem

### ISSUE THREAD

**Issue by Bunlong** [ChicagoBoss/ChicagoBoss#540]
Dear all, I can't connect to Chicagoboss websocket from client side. Whenever I run: var wsc = new WebSocket('ws://localhost:8001/websocket/message'); console.log(wsc.readyState); it alway return 0

Here is my code:

loy_message_websocket.erl
```ruby
-module(loy_message_websocket, [Req, SessionId]).
-behaviour(boss_service_handler).
init() ->
  io:format("--------------------------------------------------------init~n", []),
  {ok, []}.
```

index.html
```ruby
var wsc = new WebSocket('ws://localhost:8001/websocket/chat');
console.log(wsc.readyState); // always return 0 (can't connect)
```

Please help me to fix it, thank you!

**Comment by mihawk** [comment]
From the documentation.

 WebSocket URLs are automatically generated from the WebSocket controllers in your project's  src/websocket directory. For example, if you have myapp_**foobar**_websocket.erl, then to create a new WebSocket on the client:

```javascript
<script type="text/javascript">
  wsc = new WebSocket("ws://localhost:8001/websocket/foobar", "some_service_name");
</script>
```

**Comment by mihawk** [comment]
i guess in your case:

 ```javascript

<script type="text/javascript">
  wsc = new WebSocket("ws://localhost:8001/websocket/message");
</script>

```

**Comment by Bunlong** [comment]
@mihawk: Well, It worked well. Thank you!
