### ISSUE TITLE
./rebar boss c=test_eunit does not work

### ISSUE THREAD

**Issue by tomekowal** [ChicagoBoss/ChicagoBoss#548]
Running `./rebar boss c=test_eunit` gives:
`ERROR: boss failed while processing /Users/tomaszkowal/myapp: {'EXIT',
 {undef,
  [{rebar_erlc_compiler,doterl_compile,
...`
The `rebar_erlc_compiler:doter_compile/3` is not exported since rebar 2.1.0.
I tried using rebar 2.0.0, but it gives me another error.

**Comment by himangshuj** [comment]
same thing happens for me

**Comment by himangshuj** [comment]
works till version 8.12
seems to have been broken in 8.14

**Comment by drobakowski** [comment]
Any news on this? Does anyone maybe know a workaround or has a clue on how to fix this? I think this is pretty much a show-stopper for updating to a newer version or even for everybody who's considering to use the latest CB version as a serious web framework. :rotating_light: We're trying to update from `v0.8.13` to the latest master 74c9e3182c738f374f70743e81e3518fdfdcb819.

This isn't working with OTP `18.0` nor `17.5` (rebar 2.6.0 R15B03 20150619_161736 git 2.6.0) on a `Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64`. Previously we've used successfully a `rebar 2.2.0 R16B02 20140228_085107 git 2.2.0-20-g6e24cd6-dirty` but this version is also not working anymore.

**Comment by danikp** [comment]
This issue reported in #441 and probably fixed there. Try to use rebar binary from that commit https://github.com/ChicagoBoss/ChicagoBoss/commit/aa359d3feaba23f633dc8f02448ad6b6c98a1a2b

**Comment by danikp** [comment]
and it seems like in latest rebar version test_compile has been changed and can be used instead of doterl_compile https://github.com/rebar/rebar/blob/master/src/rebar_erlc_compiler.erl#L133
At the end, it calls it, after doing few checks, so it could be a way to solve that issue

**Comment by danikp** [comment]
ok, if we change to 
rebar_erlc_compiler:test_compile(eunit_config(Config), "eunit", ?EUNIT_DIR),

it compiles app files including tests to .eunit dir

but than, on next step it tries to start boss app and fails with 

````
INFO:  Chicago Boss compilation of app web on .eunit (ok)
Starting boss and waiting for all apps to initialize...
00:38:29.471 [info] Application mimetypes started on node nonode@nohost
ERROR: boss failed while processing /home/me/workspace/eatery/trunk/web: {'EXIT',{{badmatch,{error,{"no such file or directory","boss.app"}}},
         [{boss_rebar,boss_start,1,
                      [{file,"../ChicagoBoss/priv/rebar/boss_rebar.erl"},
                       {line,350}]},
          {boss_rebar_eunit,eunit,3,
                            [{file,"../ChicagoBoss/priv/rebar/boss_rebar_eunit.erl"},
                             {line,138}]},
          {boss_plugin,boss,2,[{file,"priv/rebar/boss_plugin.erl"},{line,33}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,491}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,416}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,300}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,259}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,91}]}]}}
````

**Comment by drobakowski** [comment]
@danikp the rebar binary version we were using was exactly the one from aa359d3feaba23f633dc8f02448ad6b6c98a1a2b, unfortunately this one is also not working anymore. Thanks for looking into this and sharing your progress so far. I'll also look deeper into this asap.

**Comment by danikp** [comment]
I just made a new app and everything worked perfectly. I also see you already made a patch, looks nice. 

Regarding warning about test suites path. rebar working with eunit, ct and qc and knows to locate their test files. i don't think we should reinvent the wheel and try to make a hack to use other directories. i.e. if it's not something we can set with rebar.config, it's better to use defaults.

**Comment by drobakowski** [comment]
@danikp yeah I personally also don't like the need for customization to include only a certain path, but I thought this could affect the originally intention behind the project layout of a CB app. If I do understand the option `eunit_compile_opts` in the [rebar.config](https://github.com/ChicagoBoss/ChicagoBoss/blob/master/skel/rebar.config#L6) right, the original behaviour could also be reproduced through `{eunit_compile_opts, [{src_dirs, ["src/test/eunit"]}]}.`? So if you're ok with eb4b5848212e22436c2103ab615c3705c1e0cd16 I can create a PR as a fix for this issue here?

**Comment by danikp** [comment]
it will be great to reproduce same behavior by only tweaking a config. PR will be appreciated. Just test if it really works please.

**Comment by danikp** [comment]
fixed in master
