### ISSUE TITLE
Cannot make a project 

### ISSUE THREAD

**Issue by roelof1967** [ChicagoBoss/ChicagoBoss#550]
Hello, 

I installed ChicagoBoss on my cloud enviroment without any problems.

But when I do make app PROJECT= Test I see this error message : 

 make app PROJECT=Test                                                                                                     
Project name should be a valid Erlang atom.                                                                                                                                            
make: *** [app] Error 1

**Comment by choptastic** [comment]
An "Erlang Atom" in this case just means "starts with a lower-case
character" (more specifically, "is a valid erlang atom without having to
add single-quotes")

make app PROJECT=test

Should do it

On Wed, Jan 28, 2015 at 11:59 AM, roelof1967 <notifications@github.com>
wrote:

> Hello,
>
> I installed ChicagoBoss on my cloud enviroment without any problems.
>
> But when I do make app PROJECT= Test I see this error message :
>
> make app PROJECT=Test
>
> Project name should be a valid Erlang atom.
>
> make: *** [app] Error 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChicagoBoss/ChicagoBoss/issues/550>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by roelof1967** [comment]
Thanks, 

That did it.
but I ran into another problem on running.
According to the must read framework  introduction I need to see a prompt when doing init-dev.sh 
But my last line is this one : 

19:48:58.931 [notice] Compile file "/home/action/workspace/test_boss/priv/init/test_boss_01_news.erl" with options [{include_dirs,["/home/action/workspace/test_boss/include"]}]   

Roelof

**Comment by choptastic** [comment]
It might just be a timing thing. Try pressing Enter a time or two.

On Wed, Jan 28, 2015 at 2:13 PM, roelof1967 <notifications@github.com>
wrote:

> Thanks,
>
> That did it.
> but I ran into another problem on running.
> According to the must read framework introduction I need to see a prompt
> when doing init-dev.sh
> But my last line is this one :
>
> 19:48:58.931 [notice] Compile file
> "/home/action/workspace/test_boss/priv/init/test_boss_01_news.erl" with
> options [{include_dirs,["/home/action/workspace/test_boss/include"]}]
>
> Roelof
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChicagoBoss/ChicagoBoss/issues/550#issuecomment-71907006>
> .
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by roelof1967** [comment]
Thanks, that did the trick.

**Comment by devappanah** [comment]
I'm getting the same problem and I'm using lower caps:

make app PROJECT=petster

After keying that in I get the following error:

WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/boss_db to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/tinymq to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/mochicow to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/erlydtl to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/jaderl to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/lfe to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/gen_smtp to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/mochiweb to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/simple_bridge to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/cowboy to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /Users/devmackbookair/ChicagoBoss/deps/iso8601 to be an app dir (containing ebin/*.app), but no .app found.
==> ChicagoBoss (create)
Writing ../petster/Makefile
Writing ../petster/rebar.config
Writing ../petster/start-server.bat
Writing ../petster/src/petster.app.src
Writing ../petster/src/view/lib/tag_modules/petster_custom_tags.erl
Writing ../petster/src/view/lib/filter_modules/petster_custom_filters.erl
Writing ../petster/boss.config
Writing ../petster/src/mail/petster_outgoing_mail_controller.erl
Writing ../petster/src/mail/petster_incoming_mail_controller.erl
Writing ../petster/priv/init/petster_01_news.erl
Writing ../petster/priv/static/chicago-boss.png
Writing ../petster/priv/static/favicon.ico
Writing ../petster/priv/petster.routes
Writing ../petster/priv/rebar/boss_plugin.erl
Writing ../petster/src/view/lib/README
Writing ../petster/init.sh
Writing ../petster/init-dev.sh
Writing ../petster/rebar
Writing ../petster/rebar.cmd
mv: rename ../petster/deps/boss/deps/* to ../petster/deps/*: No such file or directory
make: *** [app] Error 1

Appreciate any help here. @choptastic @roelof1967
