### ISSUE TITLE
[documentation/clarification request]

### ISSUE THREAD

**Issue by noizu** [ChicagoBoss/ChicagoBoss#554]
Hello I'm interested in two items and the documentation is low on info. 

1. What is the approved/best practice way for bundling database helper methods that do not require a handle.  For example  database_module:new  exists, however you may have a template to reduce lines of code for creating new entries which would leave you wanting to be able to write something like database_module:template(templateOptions). 

because of how boss_db is setup you can't simply add these to the modules. Unless I am missing something. So where do you put these helper methods. 

2. Adding additional folders to build path. 

Related to 1, the default folder layout is a little restrictive It does not allow for nested folders under lib for example that can make code organization a pain. 

It doesn't seem that you can simply go in and add an erl_opts {i, path} directive to rebar.config. I'm assuming there is some straight forward way for extending the include and compile path but I haven't been able to figure it out by grepping through the code base and rebar documentation. I realize that this may not be a chicagoboss specific documentation item but if targeting erlang neophytes to the platform it is something that will come up frequently. 

On a side note, I frequently come up against gaps in documentation and have to pour over the source code etc. to figure out the expected format of certain components. If you want someone willing to go through and flesh out documentation further by including examples, additional documentation sections and more internal implementation notes I'd be happy to do so as long as I have a few points of contacts handy for clarifying code purpose (as in why it's implemented that way or how it's implemented) and roadmap (if it will stay that way post 1.0 or not). 

www.linkedin.com/in/keithbrings

**Comment by danikp** [comment]
1) from api docs
````
BossRecords can be instantiated with either my_module:new/N (like any other parameterized module), or with boss_record:new(my_module, Attributes), where Attributes is a proplist.
````
if using second option, all parameters are optional

2) you can use rebar.config or boss.config options to extend path. Also, subdirs in /lib is something to be fixed
