### ISSUE TITLE
Wrong CB dependency in rebar.config skeleton

### ISSUE THREAD

**Issue by aherranz** [ChicagoBoss/ChicagoBoss#556]
Hi,

CB dependency in the rebar.config skeleton remains 0.8.13 in releases 0.8.14 and 0.8.15.

Regards.

**Comment by danikp** [comment]
Thanks for pointing this. Actually, we should remove that line at all. CB based project created from CB itself and downloading another copy again is not smart

**Comment by jusfeel** [comment]
It's useful sometimes, to be CB self-contained. In the v0.8.15, I "make" CB fine.But in new project, when rebar get-deps, it failed at git clone uuid ( a tag in gitorious.org. )
