### ISSUE TITLE
“context” can not be used ChicagoBoss Template Tags

### ISSUE THREAD

**Issue by laxmikantG** [ChicagoBoss/ChicagoBoss#563]
I have found that with the latest version of `ChicagoBoss i.e. 0.8.14` We can not use term `context` in template tag.

          {% if context == data.code %}
                    <option selected>{{data.value1}}</option>
                    {% else %}
                    <option selected>{{data.value2}}</option>
          {% endif %}`
OR

          `{% url action="some_action" context=data.val %}`

And here is the error thrown by ChicagoBoss

         Unhandled Error: error:{case_clause,{ok,[{"src/view/x_return/form_12.html",
                         [{{88,15},
                           erlydtl_parser,
                           ["syntax error before: ",["\"context\""]]}]}]}} Stacktrace: [{boss_web_controller_render,render_view,5,[{file,"src/boss/boss_web_controller_render.erl"},{line,217}]},{boss_web_controller,execute_action_inner,9,[{file,"src/boss/boss_web_controller.erl"},{line,290}]},{boss_web_controller_handle_request,process_dynamic_request,5,[{file,"src/boss/boss_web_controller_handle_request.erl"},{line,254}]},{boss_web_controller_handle_request,process_request,5,[{file,"src/boss/boss_web_controller_handle_request.erl"},{line,240}]},{boss_web_controller_handle_request,set_timer,8,[{file,"src/boss/boss_web_controller_handle_request.erl"},{line,160}]},{boss_web_controller_handle_request,build_dynamic_response,5,[{file,"src/boss/boss_web_controller_handle_request.erl"},{line,129}]},{boss_web_controller_handle_request,handle_request,4,[{file,"src/boss/boss_web_controller_handle_request.erl"},{line,26}]},{mochicow_upgrade,upgrade,4,[{file,"src/mochicow_upgrade.erl"},{line,72}]}]

It works pretty fine when I change `"context"` to `"cntxt"` or anything other than context.

Since I followed Django documentation but I could not see any documentation that "context" is keyword or any reserved term.

**Note** - I do have many files containing "context" used in template tags. Since not a good idea to update each file to change the term manually.

**Comment by laxmikantG** [comment]
@pius @maxlapshin @davidw  @pellegrino @darkofabijan 
Does anybody have any idea about this issue?

**Comment by choptastic** [comment]
From https://github.com/erlydtl/erlydtl/releases/tag/0.9.4:

> context is now a reserved keyword.

**Comment by laxmikantG** [comment]
@choptastic - Thank you very much! So I will have to change the term in each controller and each template manually :(

**Comment by choptastic** [comment]
You're welcome! Sorry the solution sucks. The tough part is that "context" is a common enough word that you probably can't safely just do a `sed` across all the .erl and .html files in your app.  So it'll be a painful process. Best of luck!
