### ISSUE TITLE
redirects should create absolute URL's

### ISSUE THREAD

**Issue by davidw** [ChicagoBoss/ChicagoBoss#564]
It'd be handy if redirects, in controllers, like 

    {redirect, "/noauth"}

Were automatically transformed into absolute URL's, as apparently that is the correct thing to do.

**Comment by danikp** [comment]
if i correctly recall, relative redirects are part of RFC now and fully supported by all browsers. So there is no real need to transform url to absolute path. 
And yes, you can do redirects like this.

**Comment by danikp** [comment]
closing
