### ISSUE TITLE
Error when make v0.8.14

### ISSUE THREAD

**Issue by urkh** [ChicagoBoss/ChicagoBoss#567]
Hi devs, **the error is this exactly:**

Pulling uuid from {git,"git://gitorious.org/avtobiff/erlang-uuid.git",
                       {tag,"9cfe9666f1"}}
Cloning into 'uuid'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: sh(git clone -n git://gitorious.org/avtobiff/erlang-uuid.git uuid)
failed with return code 128 and the following output:
Cloning into 'uuid'...
fatal: Could not read from remote repository.

**and this repo longer not exists**

I found the same repository hosted on github[1], I guess this was already reported, but I found nothing about it

[1]https://github.com/avtobiff/erlang-uuid

**Comment by infoir** [comment]
I have fixed this error. 
Step 1: Go to ChicagoBoss/deps/boss_db/rebar.config
Step 2: Open the rebar.config file.
Step 3: Search for {uuid, ".*",   {git, "git://gitorious.org/avtobiff/erlang-uuid.git"}
Step 4: Now replace the git:// with http:// 
It must look like this {uuid, ".*",   {git, "https://gitorious.org/avtobiff/erlang-uuid.git"}
Step 5: Now try to make again.

**Comment by danikp** [comment]
there is easier way: use CB v0.8.15  :-)

**Comment by urkh** [comment]
thanks, I have fixed it using v0.8.15.

**Comment by aherranz** [comment]
0.8.15 present this problem: https://github.com/ChicagoBoss/ChicagoBoss/issues/562.
