### ISSUE TITLE
How to connect Cassandra database with Chicago Boss Application?

### ISSUE THREAD

**Issue by infoir** [ChicagoBoss/ChicagoBoss#569]
My cassandra database is on a VMware server. The problem is that I don't find any database adapter which can help me in connecting my cassandra database with my chicago boss application. I tried Cqerl on GitHub but I am not able to use it. Can anyone tell me the procedure for connecting cassandra with chicago boss. Any proper documentation will be a great help. Thank you.

**Comment by danikp** [comment]
you can find list of supported storage drivers here https://github.com/ErlyORM/boss_db#supported-databases

instruction on how to write new database adapter located here https://github.com/ChicagoBoss/ChicagoBoss/wiki/DB-Adapter-Quickstart
