### ISSUE TITLE
Session does not expire on server side

### ISSUE THREAD

**Issue by arthurxie** [ChicagoBoss/ChicagoBoss#571]
Hi, everyone. For a serious project, we try to implement a HTTP based remote device management protocol and an user portal. When the device pool becomes large enough, there will be about 1000 sessions per second, which means CB will have to create about 1000 sessions per second. Unfortunately, I cannot find any CB server side session life time management. Without this feature, our database has to run with accumulated dead sessions.

For our project, we wish the following features to be added to boss session framework by ourselves:
1. Each write operation(create session, set session data, delete session data) refresh expire date.
2. Export two functions refresh(SessionID) and refresh(SessionID, ExpireDate) to let controller author refresh session explicitly. 
3. Start a worker process in boss_session_sup to clear expired sessions periodically.

Do I miss or misunderstand something?

**Comment by danikp** [comment]
Session lifetime can be controlled with {session_exp_time, 525600}. For all options look at the "Sessions" part of boss.config, sessions are highly configurable

**Comment by arthurxie** [comment]
Thanks for your response! But I do not think the session_exp_time option do any valuable thing on server side, it just set cookie's max_age. I did some tests with curl which accessed an URL with expired cookie and server did get the expired session data saved in backend database. In the related source code file(boss_session_*.erl and the pgsql adapter), could not find any code to delete expired session.
