### ISSUE TITLE
chicagoboss seems not support map update ?

### ISSUE THREAD

**Issue by donhwa** [ChicagoBoss/ChicagoBoss#572]
Hi!
 When I update a map data in controller, I got some error,
```erlang
test_map() ->
    M = #{a => 1},
%%    M1 = M#{a := 2}，
    M1 = M#{a := 2},
    M1.
```

Error:

 Unhandled Error: error:function_clause Stacktrace: [{boss_db_pmod_pt,expr,[{map_field_exact,91,{atom,91,a},{integer,91,2}},
                      {pmod,['Req'],
                            {7,
                            ……
                               {{test_map,0},nil,nil}}}}}],[{file,"src/boss_db_pmod_pt.erl"},{line,296}]},{boss_db_pmod_pt,expr_list,2,[{file,"src/boss_db_pmod_pt.erl"},{line,434}]},{boss_db_pmod_pt,expr,2,[{file,"src/boss_db_pmod_pt.erl"},{line,323}]},{boss_db_pmod_pt,expr,2,[{file,"src/boss_db_pmod_pt.erl"},{line,415}]},{boss_db_pmod_pt,exprs,2,[{file,"src/boss_db_pmod_pt.erl"},{line,292}]},{boss_db_pmod_pt,exprs,2,[{file,"src/boss_db_pmod_pt.erl"},{line,293}]},{boss_db_pmod_pt,clause,2,[{file,"src/boss_db_pmod_pt.erl"},{line,264}]},{boss_db_pmod_pt,clauses,2,[{file,"src/boss_db_pmod_pt.erl"},{line,256}]}] 

in master branch.

thanks :)

**Comment by kislayentronic** [comment]
I guess the problem is probably with your code. The second **comma** is something else? Here is a Unicode conversion of your code (`Unicode U+hex notation`) :- 

```
test_map() ->
    M = #{a => 1},
    M1 = M#{a := 2}U+FF0C
    M1.
```

**Comment by donhwa** [comment]
Thanks, kislayentronic  :)

Eh.. I think I made a mistake in my question post .  
The **controller** code without U+FF0C has the **map_field_exact** error yet.

**Comment by kislayentronic** [comment]
Oh, ok.
I can only suggest upgrade boss_db if its not the latest. For the rest, I guess the problem is probably with parameterized module parsing.

**Comment by donhwa** [comment]
:+1:   thank you ! I'll try and comment at boss_db.
