### ISSUE TITLE
missing destination file operand after

### ISSUE THREAD

**Issue by kev2316** [ChicagoBoss/ChicagoBoss#574]
I installed ChicagoBoss on a ubuntu server 14.04 with updated erlang, and using the rebar with the chicagoboss when performing my make which was a success. When I try to make a test app I get this error below, to when when I try and start it, it fails with a similar error pointing to the same area. What could be causing this problem? I have done quite a bit of looking around and am stumped. 

ERROR: 

ChicagoBoss$ sudo make app PROJECT=test
WARN:  Ignoring sub_dirs for /opt/dev/erlang_dev/ChicagoBoss/deps/ddb
==> ChicagoBoss (create)
Writing ../test/Makefile
Writing ../test/rebar.config
Writing ../test/start-server.bat
Writing ../test/src/test.app.src
Writing ../test/src/view/lib/tag_modules/test_custom_tags.erl
Writing ../test/src/view/lib/filter_modules/test_custom_filters.erl
Writing ../test/boss.config
Writing ../test/src/mail/test_outgoing_mail_controller.erl
Writing ../test/src/mail/test_incoming_mail_controller.erl
Writing ../test/priv/init/test_01_news.erl
Writing ../test/priv/static/chicago-boss.png
Writing ../test/priv/static/favicon.ico
Writing ../test/priv/test.routes
Writing ../test/priv/rebar/boss_plugin.erl
Writing ../test/src/view/lib/README
Writing ../test/init.sh
Writing ../test/init-dev.sh
Writing ../test/rebar
Writing ../test/rebar.cmd
cp: missing destination file operand after ‘../test/deps/boss’
Try 'cp --help' for more information.
make: *** [app] Error 1

**Comment by kev2316** [comment]
I want to know I have solved this issue. I apologize because it was a silly issue. Permission issue. Make sure the folder permissions are proper for the settings of a development environment for anyone that comes across this issue, it is most likely the only problem.

**Comment by chris-hranj** [comment]
@kev2316 can you elaborate on this? i'm running into this issue currently. i set the permission of the ../test/ directory to 777 and it still is giving me this error

**Comment by danikp** [comment]
which version of CB are you using? OS and so on....

**Comment by kev2316** [comment]
@chris-hranj basically I think the issue I had was that you need to create the project with the user that you are running it with, and I'm not sure if this applies to you, but I think I had created it with a sudo user for testing purposes just to fire things up. When I put the permissions of Chicagoboss to a normal user I was using for dev and then created the project everything was fine.
