### ISSUE TITLE
Strange error for json value.

### ISSUE THREAD

**Issue by dcy** [ChicagoBoss/ChicagoBoss#575]
Controller's code:
```
get_whitelists('GET', [], _Account) ->
    %Whitelists = [maps:to_list(Whitelist) || Whitelist <- whitelist_lib:get_sorted_whitelists()],
    %?TRACE_VAR(Whitelists),
    Whitelists = [[{is_advance, 1}, {id, 1}, {is_advanced, 1}]],
    {json, [{whitelists, Whitelists}]}.
```

javascript's code:
```
    function get_whitelists() {
        $.get("/whitelist/get_whitelists",
              {unixtime: unixtime()},
              function(data) {
                  console.log(data.whitelists);
                  model.whitelists = sort_by_key_asc(data.whitelists, "id");
              }
             )
    };
```
And console.log show is_advance is "false", not 1. is_advanced is right.
![2015-06-11-162442_202x115_scrot](https://cloud.githubusercontent.com/assets/1137238/8103179/08e702cc-1059-11e5-9161-3568fa9bd04d.png)

**Comment by aherranz** [comment]
I am curious about what was the problem.

**Comment by dcy** [comment]
It is because the javascript and my fault:
It is: "<td ms-if="whitelist.is_advanced != 1"><span class="badge">否</span></td>"
but i wrote "<td ms-if="whitelist.is_advanced = !1"><span class="badge">否</span></td>"
So "!1" is always "false"!!!
