### ISSUE TITLE
rebar compile fails

### ISSUE THREAD

**Issue by jigs2410** [ChicagoBoss/ChicagoBoss#579]
==> proper (compile)
INFO:  sh info:
        cwd: "/home/erlangdeveloper/ChicagoBoss-0.8.14/deps/proper"
        cmd: make include/compile_flags.hrl
sh: 1: exec: make: not found
ERROR: Command [compile] failed!

I dont see compile_flags.hrl under include folder for this dependency. Am i missing anything.

**Comment by danikp** [comment]
try to use latest version. Also, it will be great to know your OS and Erlang versions

**Comment by danikp** [comment]
please reopen this issue if you still have same problem
