### ISSUE TITLE
riak_pb_kv_codec.erl type dict() undefined while compiling

### ISSUE THREAD

**Issue by bdart** [ChicagoBoss/ChicagoBoss#582]
I cloned the Repo and tried it with make in the terminal but it throws this error:

`/Library/WebServer/Documents/editionf/accounting-erlang/ChicagoBoss/deps/riak_pb/src/riak_pb_kv_codec.erl:52: type dict() undefined`

repsonse of `kerl_status`:

    Available builds:
    18.0,18.0
    ----------
    Available installations:
    18.0 /Library/WebServer/Documents/editionf/accounting-erlang/ChicagoBoss
    ----------
    The current active installation is:
    /Library/WebServer/Documents/editionf/accounting-erlang/ChicagoBoss

System: Mac-OS 10.10

**Comment by frkarl** [comment]
riak_pb doesn't work with Erlang 18

https://github.com/basho/riak_pb/issues/124

**Comment by batasrki** [comment]
How does one do a ```make``` without having to compile riak_pb on Erlang 18, which does not work?

**Comment by danikp** [comment]
you can fork boss_db, comment riak as dependency and use link to your version of boss_db in CB dependency list.

**Comment by danikp** [comment]
latest master compiles on Erlang 18. Support for riak dropped for now

**Comment by jhg** [comment]
I have same error when run make in master branch and when checkout to v0.8.19

**Comment by danikp** [comment]
you cannot use riak_pb on erlang >=18

**Comment by jhg** [comment]
Someday wil be possible use? @danikp With new release of Riak, etc
