### ISSUE TITLE
Issue compiling on Ubuntu 15.04 

### ISSUE THREAD

**Issue by rivertam** [ChicagoBoss/ChicagoBoss#586]
When I run make, it fails with:

     Compiling /home/ben/Downloads/ChicagoBoss-0.8.15/deps/bson/src/bson_binary.erl failed:
     /home/ben/Downloads/ChicagoBoss-0.8.15/deps/bson/src/bson_binary.erl:55: illegal use of variable 'Name' in map
    ERROR: compile failed while processing /home/ben/Downloads/ChicagoBoss-0.8.15/deps/bson: rebar_abort

When I run

    erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell

I get back `"17"`

Besides `sudo apt-get install erlang erlang-doc` and calling `make` in the ChicagoBoss directory (both from git and downloaded from the website), I have never so much as touched Erlang, so I might be missing a dependency.

**Comment by danikp** [comment]
solved in latest version v0.8.16 and legacy branch

**Comment by rivertam** [comment]
Thank you! Legacy branch worked. This might be something to mention somewhere front-facing. I can't even tell which (if any) versions of Erlang actually work with v0.8.15.

**Comment by danikp** [comment]
none of them, This is a reason we have v0.8.16 now and v0.9.0 on it's way
I will add info about both versions, as soon as they released

**Comment by rivertam** [comment]
Cool, thanks!
