### ISSUE TITLE
Version 0.8.15 impossible to compile with Erlang 17.5

### ISSUE THREAD

**Issue by Kitton** [ChicagoBoss/ChicagoBoss#589]
Not sure where to post, here or boss_db or mongodb, but
gives me an error
```
/.../deps/bson/src/bson_binary.erl failed:
/.../deps/bson/src/bson_binary.erl:55: illegal use of variable 'Name' in map
```
because we probably should use legacy branch of bson where it's fixed, not sure though about compatibility with Erlang 18

**Comment by danikp** [comment]
use v0.8.16 instead
https://github.com/ChicagoBoss/ChicagoBoss/releases/tag/v0.8.16
