### ISSUE TITLE
Compilation error on master while trying to include macros through header files

### ISSUE THREAD

**Issue by drobakowski** [ChicagoBoss/ChicagoBoss#594]
In transition of one of our CB projects from `v0.8.13` to the latest one I've discovered some compilation errors when macros were included in source files (`src/lib`) through `-include()` of header files.

This also affects new CB projects as I could reproduce this error with a new CB app from the latest master, after merging #593 and pointing the boss dependency to the latest master 74c9e3182c738f374f70743e81e3518fdfdcb819 in the rebar.config.

```bash
> make compile-app 
./rebar boss c=compile
==> my_project_name (boss)
18:40:43.286 [error] Compile Error, "src/lib/my_project_name_lib.erl" -> [{"/private/tmp/my_project_name/include/my_project_name_lib.hrl",[{{2,24},erl_parse,["syntax error before: ",".\n"]}]},{"/private/tmp/my_project_name/src/lib/my_project_name_lib.erl",[{{var,{11,12},'TEST_MACRO'},erl_parse,["syntax error before: ","macro"]}]}]
18:40:43.286 [error] Load Module Error lib_modules : [[{"/private/tmp/my_project_name/include/my_project_name_lib.hrl",[{{2,24},erl_parse,["syntax error before: ",".\n"]}]},{"/private/tmp/my_project_name/src/lib/my_project_name_lib.erl",[{{var,{11,12},'TEST_MACRO'},erl_parse,["syntax error before: ","macro"]}]}]]
```
My environment:
```Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64```

Erlang/OTP 18.0 environment:
```Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 7.0```

Project layout:

`src/lib/my_project_name_lib.erl`:
```erlang
-module(my_project_name_lib).

-include("my_project_name_lib.hrl").

%% API
-export([
    test/0
]).

test() ->
    [{ok, ?TEST_MACRO}].
```

`include/my_project_name_lib.hrl`:
```erlang

-define(TEST_MACRO, 42).

```

`rebar.config`:
```erlang
{deps, [
  {boss, ".*", {git, "git://github.com/ChicagoBoss/ChicagoBoss.git", {tag, "74c9e3182c738f374f70743e81e3518fdfdcb819"}}}
]}.
{plugin_dir, ["priv/rebar"]}.
{plugins, [boss_plugin]}.
{eunit_compile_opts, [{src_dirs, ["src/test"]}]}.
{lib_dirs, ["../ChicagoBoss/deps/elixir/lib"]}.
```
When the `TEST_MACRO ` instead will be defined in `my_project_name_lib.erl` directly the compilation succeeds just fine. Any ideas what I could do to fix this?

**Comment by drobakowski** [comment]
In order to reproduce this easier, I've uploaded this sample project to Dropbox and you can download it [here](https://www.dropbox.com/s/41jswkqlr8q4bqe/my_project_name.tar.gz).

**Comment by danikp** [comment]
I have a strange feeling, that *.hrl files not compiled there. Same as if you have files in include/subdir/
I just guessing, we need to go deeper ;-)

**Comment by drobakowski** [comment]
Ok, I've located the bug down to `aleppo` and my PR ErlyORM/aleppo#15 should fix the previous described behaviour, even though I now get some other bugs, but this do seem to relate to `lager` and are independent to the previous one. I'll will update my example project asap to reflect this new bugs and will post a new comment.

**Comment by danikp** [comment]
ErlyORM/aleppo#15 has been merged. Please check and if  this issue have been solved, we can close it

**Comment by drobakowski** [comment]
@danikp thanks for the merge. Yes the main problem has been solved. I do have some other compilation errors in some rare corner cases but I'll open a separate ticket for that by time.

**Comment by urkh** [comment]
I have the same problem. How to solve this? 

Thanks
