### ISSUE TITLE
Compile Error (unbound_var) for validation_tests function in model greeting.erl

### ISSUE THREAD

**Issue by titpro** [ChicagoBoss/ChicagoBoss#595]
Following the "CB A Rough Introduction 0.7.0", page 19, Simple Validation
after adding the validation_tests() function

validation_tests() ->
	[{fun() -> length(GreetingText) > 0 end, "Greeting must be non-empty!"},
	 {fun() -> length(GreetingText) =< 140 end, "Greeting must be tweetable"}
	].

The erl shell reports that: 
16:30:04.511 [error] Compile Error, "src/controller/cbtutorial_greeting_controller.erl" -> [{"/Project/cbtutorial/src/controller/cbtutorial_greeting_controller.erl",[{26,erl_lint,{unbound_var,'GreetingText'}},{27,erl_lint,{unbound_var,'GreetingText'}}]}

env:
Debian 8.0
Erlang 18.0 installed via building from the erlang source code
CB latest version (03ec5667a)

What's the problem? And how to fix it? Thanks!

**Comment by danikp** [comment]
please post whole model file

**Comment by titpro** [comment]
I am very very sorry for this issue. It's my fault that put the validation_tests function into the cbtutorial_greeting_controller.erl, but it should go into greeting.erl.
