### ISSUE TITLE
deprecate usage of mochicow

### ISSUE THREAD

**Issue by danikp** [ChicagoBoss/ChicagoBoss#599]
It's unclear why we need mochicow if we use simple_bridge anyway

**Comment by choptastic** [comment]
If I have my history right, mochicow filled a gap in that simple_bridge did
not support cowboy when mochicow was built.

Bit yes, I've been meaning to find time to make this work.

I've got a little more work to do with the new version of simple_bridge and
can then kick it off.

-Jesse

**Comment by danikp** [comment]
Actually, I started to look around and finding a way to cut it off CB. Even with older version of simple_bridge. It can make upgrade to newer version much simpler.
