### ISSUE TITLE
Websockets will not work if port is not 8001

### ISSUE THREAD

**Issue by danikp** [ChicagoBoss/ChicagoBoss#609]
issue exists on both current master and development branch with simple bridge 2

**Comment by choptastic** [comment]
The client-side script is likely trying to connect specifically to port
8001.
new WebSocket("ws://localhost:8001/websocket/foobar").

Just want to make sure that the client-side is using the same port as the
application.

Also, if you're behind a reverse proxy like nginx, you need to make sure
nginx is properly forwarding the websocket requests by adding the following
rules:

        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";






On Wed, Sep 9, 2015 at 11:40 AM, Dmitry Polyanovsky <
notifications@github.com> wrote:

> issue exists on both current master and development branch with simple
> bridge 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChicagoBoss/ChicagoBoss/issues/609>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by danikp** [comment]
just figured it out. problem was on client side. closing.
