### ISSUE TITLE
Fail to render a DTL where a block is to be expanded twice in 0.8.19

### ISSUE THREAD

**Issue by aherranz** [ChicagoBoss/ChicagoBoss#615]
A base DTL, let's say `admin/layouts/admin.html`, with a block expanded in two different points:

```html
<head>
  <title>Chicago Boss Admin - {% block title %}{% endblock %}</title>
</head>
<body>
  <h1>Chicago Boss Admin - {% block title %}{% endblock %}</h1>
</body>
```

And a DTL that expands the previous one:

```html
{% extends "admin/layouts/admin.html" %}
{% block title %}General Info{% endblock %}
```

This code, in cb_admin, worked smoothly until 0.8.13. The problem is not in cb_admin (it is easy to reproduce in an out-of-the-box 0.8.19 app), I used it just to illustrate the issue.

**Comment by danikp** [comment]
not sure it is CB problem, but erlydtl. Can you try and compile same template with pure erlydtl?

also, that happens? only first block expanded?

**Comment by aherranz** [comment]
Hi Dimitry, thank you, I am afraid I am not able to compile the template with "pure erlydtl", nevertheless I downgraded to erlydtl 0.9.4 (as well as the dependencies as 0.9.4 requires) and the problem disappears.

The problem might be in erlydtl but, downgrading to 0.9.4 also solves https://github.com/ChicagoBoss/ChicagoBoss/issues/562. I am not sure if CB 0.8.19 requires erlydtl 0.10.0 (it seems they changed the public API).

**Comment by danikp** [comment]
fixed in latest master. problem was in ErlyDTL.
