### ISSUE TITLE
windows-make.bat app PROJECT=mynewproject doesn't create directory

### ISSUE THREAD

**Issue by ignaciocaamanio** [ChicagoBoss/ChicagoBoss#641]
I execute the command `windows-make.bat app PROJECT=mynewproject` but the project directory is not created.

**Comment by ignaciocaamanio** [comment]
I just realize the directory is created outside the chicagoboss directory...

**Comment by ignaciocaamanio** [comment]
I just realize the directory is created outside the chicagoboss directory...

**Comment by choptastic** [comment]
Yep, the project is created at ../mynewproject. Glad you solved it!
