### ISSUE TITLE
Compile does not work on OTP 21

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [ChicagoBoss/ChicagoBoss#675]
When I try to run the commands from the readme to compile the framework with dependencies, I get the following output:

    $ make
    ==> goldrush (get-deps)
    ==> lager (get-deps)
    ==> pmod_transform (get-deps)
    ==> erlando (get-deps)
    ==> aleppo (get-deps)
    ==> medici (get-deps)
    ==> jsx (get-deps)
    ==> ibrowse (get-deps)
    ==> ddb (get-deps)
    ==> epgsql (get-deps)
    ==> erlmc (get-deps)
    ==> mysql (get-deps)
    ==> poolboy (get-deps)
    ==> uuid (get-deps)
    ==> redo (get-deps)
    ==> ets_cache (get-deps)
    ==> proper (get-deps)
    ==> dh_date (get-deps)
    ==> tiny_pq (get-deps)
    ==> boss_test (get-deps)
    ==> boss_db (get-deps)
    ==> tinymq (get-deps)
    ==> erlydtl (get-deps)
    ==> dynamic_compile (get-deps)
    ==> jaderl (get-deps)
    ==> gen_smtp (get-deps)
    ==> iso8601 (get-deps)
    ==> mimetypes (get-deps)
    ==> mochiweb (get-deps)
    ==> cowlib (get-deps)
    ==> ranch (get-deps)
    ==> cowboy (get-deps)
    ==> simple_bridge (get-deps)
    ==> ChicagoBoss (get-deps)
    ==> goldrush (compile)
    ==> lager (compile)
    ==> pmod_transform (compile)
    ==> erlando (compile)
    ==> aleppo (compile)
    ==> medici (compile)
    ==> jsx (compile)
    ERROR: OTP release 21 does not match required regex R16|17|18|19|20
    ERROR: compile failed while processing /home/user/development/Erlang/ChicagoBoss/deps/jsx: rebar_abort
    Makefile:14: recipe for target 'compile' failed
    make: *** [compile] Error 1

I think it's a matter of allowing OTP 21 in a list of allowed releases. Since I am an Erlang beginner, let alone Erlang web frameworks, I have no idea how to fix this.

**Comment by danikp** [comment]
latest Erlang release as of few minutes ago is 20.1

**Comment by ZelphirKaltstahl** [comment]
Ah it seems I built the development version:

    $ erl --version
    Erlang/OTP 21 [DEVELOPMENT] [erts-9.0.4] [source-d66d523] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

**Comment by danikp** [comment]
closing, as Erlang 21 is still not GA version and not supported
