### ISSUE TITLE
How can I use mail_relay_use_ssl in boss.config

### ISSUE THREAD

**Issue by dachinat** [ChicagoBoss/ChicagoBoss#679]
Configuration provides `mail_relay_use_tls` option, but in my case I need 'SSL' to send messages.

Could you please help me? I need to specify something like

`{mail_relay_use_ssl, always}`

For some reason `mail_relay_use_tls` does not work. When I use other environments for sending mails like `Nodejs (Nodemailer) with secure: true` or `Ruby on Rails with ssl: true` mail arrives...

For example, following code

```
 {mail_driver, boss_mail_driver_smtp},
 {mail_relay_host, "smtp.gmail.com"},
 {mail_relay_port, 465},
 {mail_relay_username, "<my-user>@gmail.com"},
 {mail_relay_password, "<my-pass>"},
 {mail_relay_use_tls, always}
```

does not work. I tried giving `{mail_relay_use_ssl, true}` and I was getting `ssl_not_started_error`

Again, here I have tried with this example using other clients like Node.js, etc. It worked there.

Thanks.

`UPDATE`

I have managed to overcome this issue by adding

```
{application:start(asn1)},
{application:start(public_key)},
{application:start(crypto)},
{application:start(ssl)}.
```

Do you think this is a correct way? Should I be doing this differently?
I'm not an Erlang developer at all, so I don't have any clear idea what to do.

**Comment by graeme-defty** [comment]
Sorry, I just saw this. :-(

It is a long time since I did this, but I think you are OK with your solution.
I added 

  application:start(ssl),

into 

  priv/init/<myproj>_init.erl

and it has been working fine since forever.  :-)

**Comment by dachinat** [comment]
Thanks
