### ISSUE TITLE
fatal: repository 'https://github.com/layerhq/erlmc.git/' not found

### ISSUE THREAD

**Issue by ghost** [ChicagoBoss/ChicagoBoss#692]
After downloading the zip file fromhttp://chicagoboss.org/download.htm, and running the *make* command, the setup stops due the following error:

Cloning into 'erlmc'...
remote: Repository not found.
fatal: repository 'https://github.com/layerhq/erlmc.git/' not found
ERROR: sh(git clone -n https://github.com/layerhq/erlmc.git erlmc)
failed with return code 128 and the following output:
Cloning into 'erlmc'...
remote: Repository not found.
fatal: repository 'https://github.com/layerhq/erlmc.git/' not found

ERROR: 'get-deps' failed while processing /Users/pedropaulino/Desktop/ChicagoBoss-0.9-beta1/deps/boss_db: rebar_abort
make: *** [compile] Error 1

The address https://github.com/layerhq/erlmc shows a 404 error anyway.

Is there a substitute for this dependency ?

Best Regards

Pedro

**Comment by theorix** [comment]
https://github.com/theorix/erlmc
