### ISSUE TITLE
Make it possible to start additional OTP-Applications

### ISSUE THREAD

**Issue by hirschenberger** [ChicagoBoss/ChicagoBoss#75]
It should be possible to specify additional (external) OTP-Applications to be started in the `boss.conf` file. It is usefull to implement some complex backend functionality (e.g. `gen_fsm` ...)

A possible solution would be to add an `{included_applications, [myapp]}` tag to `boss.conf` which will be added to the boss application's environment.
When the boss-app is starting it evaluates this list and starts the apps in boss' supervisor.

I can try to implement it if you think it is a clean way and the feature is wanted.

**Comment by danikp** [comment]
as described in #530, there is Erlang way to do that
